name: ssr-deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.16.0]

    name: angular-deployment
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Install wrangler
        run: npm install -g wrangler

      - name: Deploy project
        run: |
          CLOUDFLARE_ACCOUNT_ID=$CLOUDFLARE_ACCOUNT_ID
          CLOUDFLARE_API_TOKEN=$CLOUDFLARE_API_TOKEN
          wrangler pages deploy dist/cloudflare --project-name ssr
        env:
          CLOUDFLARE_API_TOKEN: ${{secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{secrets.CLOUDFLARE_ACCOUNT_ID}}